name: 'Build site-yaml'
description: 'Build site-yaml'
author: 'Esther Kim'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  targetDir:
    description: 'Target Directory'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.targetDir }}
